{"uuid": "f9c514fc-3fd4-498e-ae8e-1a93373d8660", "counter": 35, "stdout": "fatal: [BEL1NA]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/local/bin/python3.7\"}, \"changed\": false, \"msg\": \"Failed to authenticate: Authentication failed.\"}\r\n...ignoring", "start_line": 29, "end_line": 31, "runner_ident": "718d818c-7768-4249-abbb-b00600cfc55d", "event": "runner_on_failed", "pid": 1964183, "created": "2020-11-02T19:10:08.316748", "parent_uuid": "0242ac1a-000b-e91c-e4c9-000000000019", "event_data": {"playbook": "main.yaml", "playbook_uuid": "5b87b9cd-e983-46f7-bb92-9f756aee7029", "play": "Interfaces", "play_uuid": "0242ac1a-000b-e91c-e4c9-000000000007", "play_pattern": "EQUIPOS", "task": "ASR SHOW INTERFACES", "task_uuid": "0242ac1a-000b-e91c-e4c9-000000000019", "task_action": "cli_command", "task_args": "", "task_path": "/usr/local/ansible/mejoras_cu1/yaml/oc.yaml:15", "host": "BEL1NA", "remote_addr": "BEL1NA", "res": {"msg": "Failed to authenticate: Authentication failed.", "invocation": {"module_args": {"command": "show int desc | exc '\"'", "newline": true, "sendonly": false, "check_all": false, "prompt": null, "answer": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/local/bin/python3.7"}, "warnings": ["Platform linux on host BEL1NA is using the discovered Python interpreter at /usr/local/bin/python3.7, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information."], "_ansible_no_log": false, "changed": false}, "start": "2020-11-02T19:09:42.708820", "end": "2020-11-02T19:10:08.316576", "duration": 25.607756, "ignore_errors": true, "event_loop": null, "uuid": "f9c514fc-3fd4-498e-ae8e-1a93373d8660"}}